---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template for a managed KIE server with a MySQL database, for Red Hat Process Automation Manager 7.0
    iconClass: icon-jboss
    tags: rhpam,jboss,xpaas
    version: 1.4.0
    openshift.io/display-name: Red Hat Process Automation Manager 7.0 managed KIE server with a MySQL database
  name: rhpam70-kieserver-mysql
labels:
  template: rhpam70-kieserver-mysql
  xpaas: 1.4.0
message: A new environment has been set up for Red Hat Process Automation Manager 7. The username/password for accessing the KIE server is ${KIE_SERVER_USER}/${KIE_SERVER_PWD}.
