---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template for a managed KIE server with a MySQL database, for Red Hat Process Automation Manager 7.0
    iconClass: icon-jboss
    tags: rhpam,jboss,xpaas
    version: 1.4.0
    openshift.io/display-name: Red Hat Process Automation Manager 7.0 managed KIE server with a MySQL database
  name: rhpam70-kieserver-mysql
labels:
  template: rhpam70-kieserver-mysql
  xpaas: 1.4.0
message: A new environment has been set up for Red Hat Process Automation Manager 7. The username/password for accessing the KIE server is ${KIE_SERVER_USER}/${KIE_SERVER_PWD}.
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: myapp
  required: true
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: openshift
  required: true
- displayName: MySQL ImageStream Tag
  description: The MySQL image version, which is intended to correspond to the MySQL version. Default is "5.7".
  name: MYSQL_IMAGE_STREAM_TAG
  value: "5.7"
  required: false
